'use client';

import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { motion } from 'framer-motion';
import { Scale, FileText, AlertTriangle, ShieldCheck, Server, AlertCircle, Lock, Mail, CheckCircle } from 'lucide-react';

export default function TermsOfService() {
  return (
    <main className="relative min-h-screen bg-slate-950 font-sans selection:bg-teal-500/30 selection:text-white">
      <Navbar />
      
      {/* Background Effects */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none -z-10">
        <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-blue-600/5 rounded-full blur-[100px] -translate-y-1/2 translate-x-1/2" />
        <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-teal-500/5 rounded-full blur-[100px] translate-y-1/2 -translate-x-1/2" />
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_at_center,black,transparent_80%)]" />
      </div>

      <div className="max-w-4xl mx-auto px-6 pt-32 pb-20">
        
        {/* Header */}
        <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
        >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-blue-500/30 bg-blue-500/10 backdrop-blur-md mb-6">
                <Scale className="w-4 h-4 text-blue-400" />
                <span className="text-sm font-semibold text-blue-300">Legal Agreement</span>
            </div>
            
            <h1 className="text-4xl md:text-5xl font-display font-bold text-white mb-6">
                Terms of Service
            </h1>
            <p className="text-slate-400">Last updated: January 24, 2026</p>
        </motion.div>

        {/* Content Container */}
        <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="bg-slate-900/50 backdrop-blur-xl border border-white/10 rounded-3xl p-8 md:p-12 space-y-16"
        >
            {/* Agreement & Acceptance */}
            <section className="space-y-6">
                <p className="text-slate-300 leading-relaxed text-lg">
                    Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the <strong className="text-white">Doctors AI</strong> application (the "Service") operated by Doctors AI / Elpisverse ("us", "we", "our").
                </p>
                <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
                    <p className="text-slate-300 text-sm leading-relaxed">
                        <strong className="text-white block mb-2">Acknowledgement & Acceptance</strong>
                        Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service. By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not use the Service.
                    </p>
                </div>
            </section>

            {/* Medical Disclaimer - CRITICAL */}
            <section className="space-y-6">
                 <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 rounded-lg bg-red-500/20">
                        <AlertTriangle className="w-6 h-6 text-red-400" />
                    </div>
                    <h2 className="text-2xl font-bold text-white">Medical Disclaimer</h2>
                </div>
                
                <div className="p-5 border-l-4 border-red-500 bg-red-500/5 rounded-r-xl">
                    <p className="text-red-200 text-sm leading-relaxed">
                        <strong className="block text-red-400 mb-2 uppercase tracking-wide text-xs font-bold">Important Notice</strong>
                        The Service is an assisting tool designed for licensed healthcare professionals. It involves the use of artificial intelligence and automation. <strong className="text-white">The Service does NOT provide medical advice, diagnosis, or treatment.</strong>
                    </p>
                </div>

                <ul className="space-y-4 text-slate-400 leading-relaxed list-disc pl-6 marker:text-red-500">
                    <li>The content generated by the Service is for informational and administrative assistance only.</li>
                    <li>You acknowledge that AI models can hallmark, generate incorrect information ("hallucinate"), or omit critical data.</li>
                    <li><strong className="text-white">Professional Responsibility:</strong> You, as the healthcare provider, are solely responsible for verifying the accuracy of all templates, reports, and AI-generated content before using them for patient care or documentation. You retain full responsibility for all medical decisions and patient outcomes.</li>
                    <li>We explicitly disclaim reliability on the Service for emergency medical situations.</li>
                </ul>
            </section>

             {/* Accounts & Membership */}
             <section className="space-y-6">
                <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 rounded-lg bg-blue-500/20">
                        <ShieldCheck className="w-6 h-6 text-blue-400" />
                    </div>
                    <h2 className="text-2xl font-bold text-white">Accounts & Security</h2>
                </div>

                <div className="space-y-4 text-slate-400 leading-relaxed">
                    <p>When you create an account with us, you must provide information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms.</p>
                    <ul className="list-disc pl-6 space-y-2 marker:text-blue-500">
                        <li>You are responsible for safeguarding the password that you use to access the Service.</li>
                        <li>You agree not to disclose your password to any third party.</li>
                        <li>You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</li>
                    </ul>
                </div>
            </section>

            {/* Intellectual Property */}
            <section className="space-y-6">
                <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 rounded-lg bg-purple-500/20">
                        <FileText className="w-6 h-6 text-purple-400" />
                    </div>
                    <h2 className="text-2xl font-bold text-white">Intellectual Property</h2>
                </div>
                <p className="text-slate-300 leading-relaxed">
                    The Service and its original content (excluding content provided by you or other users), features, and functionality are and will remain the exclusive property of Doctors AI and its licensors. The Service is protected by copyright, trademark, and other laws of both domestic and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Doctors AI.
                </p>
            </section>

             {/* User Content & Data */}
             <section className="space-y-6">
                <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 rounded-lg bg-teal-500/20">
                        <Server className="w-6 h-6 text-teal-400" />
                    </div>
                    <h2 className="text-2xl font-bold text-white">User Content & Local Storage</h2>
                </div>
                
                 <div className="grid md:grid-cols-2 gap-6">
                    <div className="p-6 rounded-2xl bg-white/5 border border-white/5">
                        <h3 className="text-lg font-semibold text-white mb-3">Your License to Us</h3>
                        <p className="text-slate-400 text-sm">
                             By submitting content (e.g., support requests, feedback), you grant us a worldwide, non-exclusive, royalty-free license to use such content to improve our Service. Note: This does NOT apply to local medical data which remains on your device.
                        </p>
                    </div>

                    <div className="p-6 rounded-2xl bg-white/5 border border-white/5">
                        <h3 className="text-lg font-semibold text-white mb-3">Local Data Responsibility</h3>
                        <p className="text-slate-400 text-sm">
                            You acknowledge that patient data is stored locally on your device. You are solely responsible for maintaining backups of your device and data. We are not liable for any loss of data resulting from device failure, theft, or app deletion.
                        </p>
                    </div>
                </div>
            </section>

            {/* Limitation of Liability - ROBUS */}
            <section className="space-y-6">
                 <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 rounded-lg bg-slate-700/50">
                        <Lock className="w-6 h-6 text-slate-300" />
                    </div>
                    <h2 className="text-2xl font-bold text-white">Limitation of Liability</h2>
                </div>
                <div className="text-slate-400 leading-relaxed space-y-4">
                    <p className="uppercase tracking-wide text-xs font-bold text-slate-500">Read Carefully</p>
                    <p>
                        In no event shall Doctors AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use, or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage.
                    </p>
                </div>
            </section>

             {/* Disclaimer of Warranty */}
             <section className="space-y-6">
                 <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 rounded-lg bg-amber-500/20">
                        <AlertCircle className="w-6 h-6 text-amber-400" />
                    </div>
                    <h2 className="text-2xl font-bold text-white">Disclaimer of Warranty</h2>
                </div>
                <p className="text-slate-300 leading-relaxed">
                    Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance.
                </p>
                <p className="text-slate-300 text-sm italic">
                    Doctors AI does not warrant that a) the Service will function uninterrupted, secure, or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.
                </p>
            </section>

            {/* Termination */}
            <section className="space-y-6">
                <h2 className="text-2xl font-bold text-white">Termination</h2>
                <p className="text-slate-300 leading-relaxed">
                    We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
                </p>
            </section>

            {/* Governing Law */}
             <section className="space-y-6">
                <h2 className="text-2xl font-bold text-white">Governing Law</h2>
                <p className="text-slate-300 leading-relaxed">
                    These Terms shall be governed and construed in accordance with the laws of India, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
                </p>
            </section>

            {/* Changes to Terms */}
            <section className="space-y-6">
                 <h2 className="text-2xl font-bold text-white">Changes to Terms</h2>
                 <p className="text-slate-300 leading-relaxed">
                    We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
                </p>
            </section>

             {/* Consent Block */}
            <section className="pt-8 border-t border-white/10">
                <div className="p-6 rounded-2xl bg-blue-500/10 border border-blue-500/20">
                     <div className="flex items-center gap-3 mb-2">
                        <CheckCircle className="w-5 h-5 text-blue-400" />
                        <h3 className="text-white font-semibold text-lg">Your Agreement</h3>
                     </div>
                     <p className="text-slate-300">
                        By installing, accessing, or using the Application, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
                    </p>
                </div>
            </section>

            {/* Contact */}
            <section className="space-y-6 pt-8">
                <h2 className="text-2xl font-bold text-white">Contact Us</h2>
                <div className="grid md:grid-cols-1 gap-6">
                    <a href="mailto:contact.doctorsai@elpisverse.com" className="p-6 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors group">
                        <h4 className="text-white font-semibold mb-2 flex items-center gap-2">
                           <Mail className="w-4 h-4 text-teal-400" /> Legal & General Inquiries
                        </h4>
                        <p className="text-slate-400 text-sm group-hover:text-teal-400 transition-colors">contact.doctorsai@elpisverse.com</p>
                    </a>
                </div>
            </section>

        </motion.div>
      </div>

      <Footer />
    </main>
  );
}
